// Generated by CoffeeScript 1.4.0
var app, connect, port, server, sharejs, sharejsOpts;

connect = require('connect');

sharejs = require('share').server;

sharejsOpts = {
  browserChannel: {
    cors: "*"
  },
  db: "none"
};

app = connect();

app.use(connect['static'](__dirname + "/../static"));

server = sharejs.attach(app, sharejsOpts);

port = 5000;

server.listen(port, function() {
  return console.log("Listening on " + port);
});
