// Generated by CoffeeScript 1.3.3
var connect, port, server, sharejs, sharejsOpts;

connect = require('connect');

sharejs = require('share').server;

sharejsOpts = {
  browserChannel: {
    cors: "*"
  },
  db: "none"
};

server = connect.createServer();

server.use(connect['static'](__dirname + "/../static"));

sharejs.attach(server, sharejsOpts);

port = 5000;

server.listen(port, function() {
  return console.log("Listening on " + port);
});
